# Generated by Django 5.0.6 on 2025-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-created'], 'verbose_name': 'CURSO', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='codCurso',
            field=models.CharField(max_length=12, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nameCurso',
            field=models.TextField(verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='turnoCurso',
            field=models.CharField(max_length=10, verbose_name='Turno del curso'),
        ),
    ]
