# Generated by Django 5.0.6 on 2025-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_options_alter_cursos_codcurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía del curso'),
        ),
    ]
