# Generated by Django 5.0.6 on 2025-06-26 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_becas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becas',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Beca a aplicar'),
        ),
    ]
