# Generated by Django 5.0.6 on 2025-06-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_becas_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='costo',
            field=models.FloatField(default=0.0, verbose_name='Costo del curso'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='cupo_maximo',
            field=models.IntegerField(default=30, verbose_name='Cupo máximo del curso'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Se encuentra habilitado el curso?'),
        ),
    ]
