# Generated by Django 5.0.6 on 2025-06-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_cursos_costo_cursos_cupo_maximo_cursos_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
