# Generated by Django 5.0.6 on 2025-07-16 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso'),
        ),
    ]
