# Generated by Django 5.0.6 on 2025-07-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_comentario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariocontacto',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.cursos'),
        ),
    ]
